apiVersion: apps/v1
kind: Deployment
metadata:
  name: openclaw
  namespace: openclaw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openclaw
  template:
    metadata:
      labels:
        app: openclaw
    spec:
      containers:
      - name: openclaw
        image: ghcr.io/samhatter/openclaw:latest
        command: ["node"]
        args: ["dist/index.js", "gateway", "--bind", "lan", "--port", "18789"]
        env:
        - name: GOG_CREDENTIALS_DIR
          value: /app/gog-creds
        volumeMounts:
        - name: clawdbot-config
          mountPath: /home/node/.openclaw
        - name: clawdbot-workspace
          mountPath: /home/node/clawd
        - name: clawdbot-templates
          mountPath: /app/docs/reference/templates
        - name: gog-creds
          mountPath: /app/gog-creds/credentials.json
      volumes:
      - name: clawdbot-config
        hostPath:
          path: /storage/appdata/openclaw/config
          type: DirectoryOrCreate
      - name: clawdbot-workspace
        hostPath:
          path: /storage/appdata/openclaw/workspace
          type: DirectoryOrCreate
      - name: clawdbot-templates
        hostPath:
          path: /storage/appdata/openclaw/templates
          types: DirectoryOrCreate
      - name: gog-creds
        hostPath:
          path: /storage/appdata/openclaw/config/credentials/gog/credentials.json
          type: FileOrCreate
      ports:
      - containerPort: 18789
        name: api
      - containerPort: 18790
        name: control
