apiVersion: apps/v1
kind: Deployment
metadata:
  name: openclaw
  namespace: openclaw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openclaw
  template:
    metadata:
      labels:
        app: openclaw
    spec:
      containers:
      - name: openclaw
        image: moltbot/moltbot:latest
        env:
        - name: CLAWDBOT_GATEWAY_TOKEN
          valueFrom:
            secretKeyRef:
              name: gateway-secret
              key: CLAWDBOT_GATEWAY_TOKEN
        volumeMounts:
        - name: clawdbot-config
          mountPath: /home/node/.moltbot
        - name: clawdbot-workspace
          mountPath: /home/node/clawd
        - name: clawdbot-templates
          mountPath: /app/docs/reference/templates
      volumes:
      - name: clawdbot-config
        hostPath:
          path: /storage/appdata/openclaw/config
          type: DirectoryOrCreate
      - name: clawdbot-workspace
        hostPath:
          path: /storage/appdata/openclaw/workspace
          type: DirectoryOrCreate
      - name: clawdbot-templates
        hostPath:
          path: /storage/appdata/openclaw/templates
          types: DirectoryOrCreate
      ports:
      - containerPort: 18789
        name: api
      - containerPort: 18790
        name: control
