apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../secrets/arcanis
  - flux-system
  - traefik
  - homepage
  - plex
  - sonarr
  - radarr
  - prowlarr
  - randomart
  - unifi
  - ddns
  - adguard
  - qbittorrent
