apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-values
  namespace: traefik
data:
  values.yaml: |
    entryPoints:
      web:
        address: :80
      websecure:
        address: :443

    certificatesResolvers:
      letsencrypt:
        acme:
          email: sammyvincent2001@gmail.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web

    ports:
      web:
        port: 80
      websecure:
        port: 443

    persistence:
      enabled: true
      size: 1Gi
      path: /data
      accessMode: ReadWriteOnce
