apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-values
  namespace: traefik
data:
  values.yaml: |
    additionalArguments:
      - --certificatesresolvers.letsencrypt.acme.email=sammyvincent2001@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web

    ports:
      web:
        port: 80
      websecure:
        port: 443

    persistence:
      enabled: true
      size: 1Gi
      path: /data
      accessMode: ReadWriteOnce
