apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-call
  namespace: matrix-call
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: element-call
  template:
    metadata:
      labels:
        app: element-call
    spec:
      containers:
      - name: element-call
        image: ghcr.io/element-hq/element-call:latest
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: element-call-config
          mountPath: /app/config.json
          subPath: config.json
      volumes:
      - name: element-call-config
        hostPath:
          path: /storage/appdata/matrix-call
          type: Directory
