apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: element-call
  namespace: matrix-call
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`call.samantha-home-server.net`)
      kind: Rule
      services:
        - name: element-call
          port: 8080
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lk-jwt-service
  namespace: matrix-call
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sfu-jwt.samantha-home-server.net`)
      kind: Rule
      services:
        - name: lk-jwt-service
          port: 8080
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: livekit
  namespace: matrix-call
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sfu.samantha-home-server.net`)
      kind: Rule
      services:
        - name: livekit
          port: 7880
  tls:
    certResolver: letsencrypt
