apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: matrix-call
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: livekit-sfu
  namespace: matrix-call
spec:
  type: ClusterIP
  selector:
    app: livekit
  ports:
  - port: 7880
    targetPort: 7880
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: lk-jwt-service
  namespace: matrix-call
spec:
  selector:
    app: lk-jwt-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: element-call
  namespace: matrix-call
spec:
  selector:
    app: element-call
  ports:
  - port: 8080
    targetPort: 8080
    name: http
