apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.sops.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
  - cadvisor-daemonset.yaml
  - node-exporter-daemonset.yaml
  - service.yaml
  - ingress.yaml
