apiVersion: v1
kind: Secret
metadata:
    name: slskd-name-reservation-bot-config
    namespace: slskd-name-reservation-bot
type: Opaque
stringData:
    slskd-slsk-password: ENC[AES256_GCM,data:DSoriRdFPe2arDA=,iv:2DWObH9JvSA8sPdnEsO5Yb3Wu6i3y6cokONIx0r2pxk=,tag:MnM8I18nUxtHG61e7asXaQ==,type:str]
sops:
    age:
        - recipient: age1n7m4qddze6jmky0zzgasxr2fsea25t4ejppzv0flftsuzhrytgaqm49c2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPblZ6SHhKblJseXliNHV3
            bWdXUGhrcEpBdGN6M1FyWTZBancweVRaZ0djCjdIK0xhb1pqRTZPUUVmZmdzVEpB
            U2k2SVFCTHhLL2pIcDhjNzhDdTRiQkkKLS0tIE52QWF4UndDUFhDZzQ5bjlIRUJN
            cHZkUGt5MGNueDlmZ0k1RGZFMHhEb00KEU1C2wczSo3AJM737MlmLkF/T/9kMFFZ
            M6DRtleAJtPXYVM+gmUjyYUlfTOBgM+DSA5jeFMDJr1SWKfAVePiHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T20:02:45Z"
    mac: ENC[AES256_GCM,data:VvP9k8aPHsalmwgCaJ3uCwiK4IFaF5uXACEcV3aXasqULO5Evm35LUv0zLEw9HOlpso6spAJn93t/YYnB9mZ6YNZmKSRCFo5U9nZCeLA4rFZyHSL/tY5tkSc2THgBCk+zt30WrX6NWQ9z9ROC1sRjwdztpHCcDnsEH1zivEZ05U=,iv:3VuWJnP3zACC9PLdyenH5nK/e5kRHt2iy2D7HJUjcmw=,tag:Sw6WPVPmEV3PzYkBaOtyfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0