apiVersion: v1
kind: Secret
metadata:
    name: slskd-name-reservation-bot-config
    namespace: slskd-name-reservation-bot
type: Opaque
stringData:
    slskd-slsk-password: ENC[AES256_GCM,data:LaOpytPjTxxOtQ==,iv:CLqITd1DNWt0o+8S8ubUJNUk1mEdyANGcOiILA2s8Ds=,tag:1NFmZM79FpL8WZG+dqGaTQ==,type:str]
sops:
    age:
        - recipient: age1n7m4qddze6jmky0zzgasxr2fsea25t4ejppzv0flftsuzhrytgaqm49c2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPblZ6SHhKblJseXliNHV3
            bWdXUGhrcEpBdGN6M1FyWTZBancweVRaZ0djCjdIK0xhb1pqRTZPUUVmZmdzVEpB
            U2k2SVFCTHhLL2pIcDhjNzhDdTRiQkkKLS0tIE52QWF4UndDUFhDZzQ5bjlIRUJN
            cHZkUGt5MGNueDlmZ0k1RGZFMHhEb00KEU1C2wczSo3AJM737MlmLkF/T/9kMFFZ
            M6DRtleAJtPXYVM+gmUjyYUlfTOBgM+DSA5jeFMDJr1SWKfAVePiHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T20:27:24Z"
    mac: ENC[AES256_GCM,data:xERQjm7h5ClYpY4jtSLpZ6eHboeKJkhaKkfi7z9/4MnfnF8yWjKrJxTZFqHXZnMIS37lOwzHqS56gQvhOaevDd8fcWUCZALUeh9oRjY0FZPkwM9qmGvS9cP2tKTBYoBc8VfZRvtafy9CbYuBFZ1/TB4mHxF7ngSZdDNRzNKTAAI=,iv:Nzf9YuBn2fa6sWAJIHIAoR3r4t196qLqlde52wBVdJM=,tag:mIMA3Dl4zW6wEDTPEsv0cA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
